# site settings
title: Sofia Cecic
subtitle: Mechanical Design Engineer | Tesla
email: [Your Email Address]
description: Mechanical Design Engineer at Tesla working on residential energy products. <br /> Ironman 70.3 Triathlete.
baseurl: "" # Leave empty if this is your main github.io repo
url: "https://Sofiacecic.github.io"
author: Sofia Cecic
street_address: 
city: Palo Alto
state: CA
zip_code: 
country: USA

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
socials:
  GitHub: https://github.com/Sofiacecic
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/sofiacecic
  LinkedIn: # Paste your LinkedIn URL here
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
